repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.4.0  # Use the ref you want to point at
        hooks:
            -   id: trailing-whitespace
            -   id: check-added-large-files
            -   id: check-ast
            -   id: check-case-conflict
            -   id: check-docstring-first
            -   id: check-executables-have-shebangs
            -   id: check-json
            -   id: check-merge-conflict
            -   id: check-toml
            -   id: check-yaml
            -   id: debug-statements
            -   id: detect-aws-credentials
            -   id: detect-private-key
            -   id: end-of-file-fixer
            -   id: requirements-txt-fixer
    -   repo: https://github.com/asottile/pyupgrade
        rev: v3.13.0
        hooks:
            -   id: pyupgrade
                args: [ --py311-plus ]
    -   repo: https://github.com/pre-commit/mirrors-isort
        rev: v5.10.1
        hooks:
            -   id: isort
                exclude: ^.venv/|^.vscode/|^venv/
                args: ["--profile", "black"]
    -   repo: https://github.com/psf/black
        rev: 23.9.1
        hooks:
            -   id: black
                language_version: python3.11
                args:
                    - --safe
                    - --quiet
                    - --line-length=120
    -   repo: https://github.com/PyCQA/flake8
        rev: 6.1.0
        hooks:
            -   id: flake8
